### ISSUE TITLE
Behavior changes: Apps targeting Android 13 or higher

### ISSUE THREAD

**Issue by hoangchungk53qx1** [FunkyMuse/MediaPicker#7]
I have opened 1 MR about changing permission on SDK 33 , I have attached related documents
https://developer.android.com/about/versions/13/behavior-changes-13

MR 👍 
https://github.com/FunkyMuse/MediaPicker/pull/6

**Comment by FunkyMuse** [comment]
i'll look into it, happy new year

**Comment by FunkyMuse** [comment]
Thanks for the PR, good job
